#ifndef DEF_USERMOOD_DEFINITIONS_H
#define DEF_USERMOOD_DEFINITIONS_H

//Namespaces

#define MOOD_PROTOCOL_URL "http://jabber.org/protocol/mood"
#define MOOD_NOTIFY_PROTOCOL_URL "http://jabber.org/protocol/mood+notify"

#define RSR_STORAGE_MOODICONS "moodicons"

//MoodCatalog
#define MOOD_NULL "null"
#define MOOD_AFRAID "afraid"
#define MOOD_AMAZED "amazed"
#define MOOD_ANGRY "angry"
#define MOOD_AMOROUS "amorous"
#define MOOD_ANNOYED "annoyed"
#define MOOD_ANXIOUS "anxious"
#define MOOD_AROUSED "aroused"
#define MOOD_ASHAMED "ashamed"
#define MOOD_BORED "bored"
#define MOOD_BRAVE "brave"
#define MOOD_CALM "calm"
#define MOOD_CAUTIOUS "cautious"
#define MOOD_COLD "cold"
#define MOOD_CONFIDENT "confident"
#define MOOD_CONFUSED "confused"
#define MOOD_CONTEMPLATIVE "contemplative"
#define MOOD_CONTENTED "contented"
#define MOOD_CRANKY "cranky"
#define MOOD_CRAZY "crazy"
#define MOOD_CREATIVE "creative"
#define MOOD_CURIOUS "curious"
#define MOOD_DEJECTED "dejected"
#define MOOD_DEPRESSED "depressed"
#define MOOD_DISAPPOINTED "disappointed"
#define MOOD_DISGUSTED "disgusted"
#define MOOD_DISMAYED "dismayed"
#define MOOD_DISTRACTED "distracted"
#define MOOD_EMBARRASSED "embarrassed"
#define MOOD_ENVIOUS "envious"
#define MOOD_EXCITED "excited"
#define MOOD_FLIRTATIOUS "flirtatious"
#define MOOD_FRUSTRATED "frustrated"
#define MOOD_GRUMPY "grumpy"
#define MOOD_GUILTY "guilty"
#define MOOD_HAPPY "happy"
#define MOOD_HOPEFUL "hopeful"
#define MOOD_HOT "hot"
#define MOOD_HUMBLED "humbled"
#define MOOD_HUMILIATED "humiliated"
#define MOOD_HUNGRY "hungry"
#define MOOD_HURT "hurt"
#define MOOD_IMPRESSED "impressed"
#define MOOD_IN_AWE "in_awe"
#define MOOD_IN_LOVE "in_love"
#define MOOD_INDIGNANT "indignant"
#define MOOD_INTERESTED "interested"
#define MOOD_INTOXICATED "intoxicated"
#define MOOD_INVINCIBLE "invincible"
#define MOOD_JEALOUS "jealous"
#define MOOD_LONELY "lonely"
#define MOOD_LUCKY "lucky"
#define MOOD_MEAN "mean"
#define MOOD_MOODY "moody"
#define MOOD_NERVOUS "nervous"
#define MOOD_NEUTRAL "neutral"
#define MOOD_OFFENDED "offended"
#define MOOD_OUTRAGED "outraged"
#define MOOD_PLAYFUL "playful"
#define MOOD_PROUD "proud"
#define MOOD_RELAXED "relaxed"
#define MOOD_RELIEVED "relieved"
#define MOOD_REMORSEFUL "remorseful"
#define MOOD_RESTLESS "restless"
#define MOOD_SAD "sad"
#define MOOD_SARCASTIC "sarcastic"
#define MOOD_SERIOUS "serious"
#define MOOD_SHOCKED "shocked"
#define MOOD_SHY "shy"
#define MOOD_SICK "sick"
#define MOOD_SLEEPY "sleepy"
#define MOOD_SPONTANEOUS "spontaneous"
#define MOOD_STRESSED "stressed"
#define MOOD_STRONG "strong"
#define MOOD_SURPRISED "surprised"
#define MOOD_THANKFUL "thankful"
#define MOOD_THIRSTY "thirsty"
#define MOOD_TIRED "tired"
#define MOOD_UNDEFINED "undefined"
#define MOOD_WEAK "weak"
#define MOOD_WORRIED "worried"

//UserMood Icons
#define UMI_AFRAID "afraid"
#define UMI_AMAZED "amazed"
#define UMI_ANGRY "angry"
#define UMI_AMOROUS "amorous"
#define UMI_ANNOYED "annoyed"
#define UMI_ANXIOUS "anxious"
#define UMI_AROUSED "aroused"
#define UMI_ASHAMED "ashamed"
#define UMI_BORED "bored"
#define UMI_BRAVE "brave"
#define UMI_CALM "calm"
#define UMI_CAUTIOUS "cautious"
#define UMI_COLD "cold"
#define UMI_CONFIDENT "confident"
#define UMI_CONFUSED "confused"
#define UMI_CONTEMPLATIVE "contemplative"
#define UMI_CONTENTED "contented"
#define UMI_CRANKY "cranky"
#define UMI_CRAZY "crazy"
#define UMI_CREATIVE "creative"
#define UMI_CURIOUS "curious"
#define UMI_DEJECTED "dejected"
#define UMI_DEPRESSED "depressed"
#define UMI_DISAPPOINTED "disappointed"
#define UMI_DISGUSTED "disgusted"
#define UMI_DISMAYED "dismayed"
#define UMI_DISTRACTED "distracted"
#define UMI_EMBARRASSED "embarrassed"
#define UMI_ENVIOUS "envious"
#define UMI_EXCITED "excited"
#define UMI_FLIRTATIOUS "flirtatious"
#define UMI_FRUSTRATED "frustrated"
#define UMI_GRUMPY "grumpy"
#define UMI_GUILTY "guilty"
#define UMI_HAPPY "happy"
#define UMI_HOPEFUL "hopeful"
#define UMI_HOT "hot"
#define UMI_HUMBLED "humbled"
#define UMI_HUMILIATED "humiliated"
#define UMI_HUNGRY "hungry"
#define UMI_HURT "hurt"
#define UMI_IMPRESSED "impressed"
#define UMI_IN_AWE "in_awe"
#define UMI_IN_LOVE "in_love"
#define UMI_INDIGNANT "indignant"
#define UMI_INTERESTED "interested"
#define UMI_INTOXICATED "intoxicated"
#define UMI_INVINCIBLE "invincible"
#define UMI_JEALOUS "jealous"
#define UMI_LONELY "lonely"
#define UMI_LUCKY "lucky"
#define UMI_MEAN "mean"
#define UMI_MOODY "moody"
#define UMI_NERVOUS "nervous"
#define UMI_NEUTRAL "neutral"
#define UMI_OFFENDED "offended"
#define UMI_OUTRAGED "outraged"
#define UMI_PLAYFUL "playful"
#define UMI_PROUD "proud"
#define UMI_RELAXED "relaxed"
#define UMI_RELIEVED "relieved"
#define UMI_REMORSEFUL "remorseful"
#define UMI_RESTLESS "restless"
#define UMI_SAD "sad"
#define UMI_SARCASTIC "sarcastic"
#define UMI_SERIOUS "serious"
#define UMI_SHOCKED "shocked"
#define UMI_SHY "shy"
#define UMI_SICK "sick"
#define UMI_SLEEPY "sleepy"
#define UMI_SPONTANEOUS "spontaneous"
#define UMI_STRESSED "stressed"
#define UMI_STRONG "strong"
#define UMI_SURPRISED "surprised"
#define UMI_THANKFUL "thankful"
#define UMI_THIRSTY "thirsty"
#define UMI_TIRED "tired"
#define UMI_UNDEFINED "undefined"
#define UMI_WEAK "weak"
#define UMI_WORRIED "worried"

//RostersView - ContextMenu
#define AG_RVCM_USERMOOD 300


//MenuIcons
#define MNI_TRIVIALPLUGIN_MESSAGE "trivialpluginMessage"

//Notification Types
#define NNT_USERMOOD "UserMoodNotify"

//Notification Type Orders
#define NTO_USERMOOD_NOTIFY 275

//Menu Icons
#define MNI_USERMOOD "usermood"

//Options
#define OPV_UT_SHOW_ROSTER_LABEL "show-roster-label"

//Opton Nodes
#define OPN_USERMOOD "UserMood"

//Option Node Order
#define ONO_USERMOOD 865

//Option Widget Order
#define OWO_USERMOOD 510

//Roster Label Order
#define RLO_USERMOOD			RLAP_RIGHT_TOP + 260

//Roster ToolTip Order
#define RTTO_USERMOOD			920

#endif //DEF_USERMOOD_DEFINITIONS_H
